name: Deployment of Lambda Function using GitHub Actions

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Zip Tool
        run: sudo apt-get install -y zip

      - name: Create Zip File for Lambda Function
        run: zip -r code.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Deploy Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:eu-west-2:574679457009:function:Lambda_function \
            --zip-file fileb://code.zip
